# Generated by Django 6.0.7 on 2026-07-15 10:18

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apropos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apropospage',
            name='intro',
            field=models.TextField(blank=True, default="Cabinet de consulting et de formation en géomatique basé à Ouagadougou, Burkina Faso. Nous mettons l'expertise géospatiale au service du développement durable en Afrique.", verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='apropospage',
            name='mission',
            field=models.TextField(default='Fournir des solutions géospatiales innovantes et accessibles qui permettent aux organisations africaines de prendre des décisions éclairées basées sur la donnée territoriale.', verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='apropospage',
            name='valeurs',
            field=wagtail.fields.RichTextField(blank=True, help_text='Utilisé comme fallback si les valeurs statiques ne conviennent pas.', verbose_name='Valeurs (texte riche)'),
        ),
        migrations.AlterField(
            model_name='apropospage',
            name='vision',
            field=models.TextField(default="Être le cabinet de référence en géomatique en Afrique de l'Ouest, reconnu pour l'excellence technique, le transfert de compétences et l'impact sur le développement local.", verbose_name='Vision'),
        ),
        migrations.AlterField(
            model_name='etapetimeline',
            name='est_actuel',
            field=models.BooleanField(default=False, verbose_name='Étape actuelle (couleur navy)'),
        ),
        migrations.AlterField(
            model_name='etapetimeline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='etapetimeline',
            name='titre',
            field=models.CharField(max_length=200, verbose_name="Titre de l'étape"),
        ),
        migrations.AlterField(
            model_name='membreequipe',
            name='competences',
            field=models.CharField(blank=True, help_text='Ex : SIG, Django, WebMapping', max_length=300, verbose_name='Compétences (séparées par des virgules)'),
        ),
        migrations.AlterField(
            model_name='membreequipe',
            name='couleur_bg',
            field=models.CharField(blank=True, default='linear-gradient(135deg,#1A3A8F,#29ABE2)', max_length=100, verbose_name='Couleur de fond avatar (CSS gradient ou hex)'),
        ),
        migrations.AlterField(
            model_name='membreequipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='membreequipe',
            name='initiales',
            field=models.CharField(max_length=3, verbose_name='Initiales (ex: BW)'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
