# Generated by Django 5.2.14 on 2026-07-15 19:59

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apropos', '0002_alter_apropospage_intro_alter_apropospage_mission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapetimeline',
            options={'ordering': ['ordre'], 'verbose_name': 'Étape timeline', 'verbose_name_plural': 'Étapes timeline'},
        ),
        migrations.AlterModelOptions(
            name='membreequipe',
            options={'ordering': ['ordre'], 'verbose_name': "Membre de l'équipe", 'verbose_name_plural': "Membres de l'équipe"},
        ),
        migrations.AlterModelOptions(
            name='partenaire',
            options={'ordering': ['ordre'], 'verbose_name': 'Partenaire', 'verbose_name_plural': 'Partenaires'},
        ),
        migrations.RemoveField(
            model_name='etapetimeline',
            name='page',
        ),
        migrations.RemoveField(
            model_name='etapetimeline',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='membreequipe',
            name='page',
        ),
        migrations.RemoveField(
            model_name='membreequipe',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='page',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='etapetimeline',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AddField(
            model_name='membreequipe',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='apropospage',
            name='intro',
            field=models.TextField(blank=True, default='Cabinet de consulting et de formation en géomatique basé à Ouagadougou, Burkina Faso.'),
        ),
        migrations.AlterField(
            model_name='apropospage',
            name='mission',
            field=models.TextField(default='Fournir des solutions géospatiales innovantes et accessibles.', verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='apropospage',
            name='valeurs',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Valeurs'),
        ),
        migrations.AlterField(
            model_name='apropospage',
            name='vision',
            field=models.TextField(default="Être le cabinet de référence en géomatique en Afrique de l'Ouest.", verbose_name='Vision'),
        ),
        migrations.AlterField(
            model_name='etapetimeline',
            name='est_actuel',
            field=models.BooleanField(default=False, verbose_name='Étape actuelle'),
        ),
        migrations.AlterField(
            model_name='etapetimeline',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='membreequipe',
            name='competences',
            field=models.CharField(blank=True, max_length=300, verbose_name='Compétences (séparées par virgules)'),
        ),
        migrations.AlterField(
            model_name='membreequipe',
            name='couleur_bg',
            field=models.CharField(blank=True, default='linear-gradient(135deg,#1A3A8F,#29ABE2)', max_length=100, verbose_name='Couleur avatar'),
        ),
        migrations.AlterField(
            model_name='membreequipe',
            name='initiales',
            field=models.CharField(max_length=3, verbose_name='Initiales'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='emoji',
            field=models.CharField(blank=True, default='🏢', max_length=4),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='nom',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
    ]
