[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["pip install -r requirements.txt", "npm install"]

[phases.build]
cmds = ["npm run build:css", "python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate --noinput && gunicorn innovgeomatic.wsgi:application --bind 0.0.0.0:$PORT --timeout 120"