# Generated by Django 5.2.14 on 2026-07-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='email_destinataire',
            field=models.EmailField(blank=True, default='contact@innovgeomatic.com', help_text='Adresse qui reçoit les notifications de nouveaux messages.', max_length=254, verbose_name='Email destinataire des messages'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='horaires',
            field=models.TextField(blank=True, default='Lun–Ven : 08h–17h | Sam : 09h–13h', verbose_name='Horaires'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='intro',
            field=models.TextField(blank=True, default='Une question, un projet ou une demande de devis ? Notre équipe vous répond sous 24h ouvrées.', verbose_name='Introduction'),
        ),
    ]
