# Generated by Django 5.2.14 on 2026-07-14 07:11

import modelcluster.contrib.taggit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPostTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='intro',
            field=models.TextField(blank=True, default="Tutoriels, actualités SIG, télédétection et cartographie web — par l'équipe Innov Geomatics.", verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='chapeau',
            field=models.TextField(blank=True, help_text="Résumé affiché sur les cards et en intro de l'article.", verbose_name='Chapeau (introduction)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='est_phare',
            field=models.BooleanField(default=False, help_text='Affiché en grand en haut du blog.', verbose_name='Article phare'),
        ),
    ]
