# Generated by Django 5.2.14 on 2026-07-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': "Page d'accueil"},
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default="Innov Geomatics Consulting accompagne les organisations dans leurs projets SIG, télédétection et cartographie web — de Ouagadougou à l'ensemble du continent.", verbose_name='Sous-titre héro'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_countries',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_projects',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_trained',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
