# Generated by Django 5.2.14 on 2026-07-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='description_courte',
            field=models.TextField(help_text='Affichée sur les cards.', verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='est_phare',
            field=models.BooleanField(default=False, help_text='Affiche ce projet en grand en haut de la liste.', verbose_name='Projet phare'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='technologies',
            field=models.CharField(blank=True, help_text='Ex : Django, PostGIS, Leaflet.js, QGIS', max_length=500, verbose_name='Technologies (séparées par des virgules)'),
        ),
        migrations.AlterField(
            model_name='projetsindexpage',
            name='intro',
            field=models.TextField(blank=True, default='Du SIG foncier à la cartographie web, découvrez nos réalisations pour des institutions publiques, ONG et entreprises privées.', verbose_name='Introduction'),
        ),
    ]
