# Generated by Django 5.2.14 on 2026-07-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='description_courte',
            field=models.TextField(help_text='Affichée sur les cards.', verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='duree',
            field=models.CharField(blank=True, max_length=60, verbose_name='Durée (ex : 5 jours)'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='est_disponible',
            field=models.BooleanField(default=False, help_text="Cocher pour afficher le bouton 'S'inscrire' et le badge 'Disponible'.", verbose_name="Disponible à l'inscription"),
        ),
        migrations.AlterField(
            model_name='formation',
            name='nb_participants',
            field=models.CharField(blank=True, max_length=60, verbose_name='Participants (ex : 8–15 pers.)'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='prix',
            field=models.PositiveIntegerField(blank=True, help_text="Laisser vide si le prix n'est pas encore défini.", null=True, verbose_name='Prix (FCFA)'),
        ),
        migrations.AlterField(
            model_name='formationsindexpage',
            name='intro',
            field=models.TextField(blank=True, default='Des programmes pratiques animés par des experts terrain, en présentiel à Ouagadougou ou en ligne. Certifiés et adaptés au contexte africain.', verbose_name='Introduction'),
        ),
    ]
