# Generated by Django 5.2.14 on 2026-07-19 00:07

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_alter_formation_description_courte_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='avec_certificat',
            field=models.BooleanField(default=True, verbose_name='Certificat inclus'),
        ),
        migrations.AddField(
            model_name='formation',
            name='certificat_description',
            field=models.TextField(blank=True, default='Délivré après validation du projet final. Téléchargeable en PDF avec QR code de vérification.', verbose_name='Description du certificat'),
        ),
        migrations.AddField(
            model_name='formation',
            name='emoji_fallback',
            field=models.CharField(blank=True, default='🎓', max_length=4, verbose_name='Emoji fallback'),
        ),
        migrations.AddField(
            model_name='formation',
            name='langue',
            field=models.CharField(blank=True, default='Français', max_length=60, verbose_name='Langue'),
        ),
        migrations.AddField(
            model_name='formation',
            name='materiel',
            field=models.CharField(blank=True, max_length=120, verbose_name='Matériel fourni'),
        ),
        migrations.AddField(
            model_name='formation',
            name='niveau',
            field=models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('tous', 'Tous niveaux')], default='debutant', max_length=20),
        ),
        migrations.AddField(
            model_name='formation',
            name='prix_description',
            field=models.CharField(blank=True, default='Par participant · Déjeuners inclus · Support de cours PDF', max_length=200, verbose_name='Description du prix'),
        ),
        migrations.AddField(
            model_name='formation',
            name='prochaine_session',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prochaine session (ex : Août 2025)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='tdr_contexte',
            field=models.TextField(blank=True, verbose_name='Contexte et justification'),
        ),
        migrations.AddField(
            model_name='formation',
            name='tdr_methodologie',
            field=models.TextField(blank=True, verbose_name='Méthodologie'),
        ),
        migrations.AddField(
            model_name='formation',
            name='tdr_objectifs',
            field=models.TextField(blank=True, verbose_name='Objectifs généraux (un par ligne)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='tdr_public',
            field=models.TextField(blank=True, verbose_name='Public cible (un par ligne)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='tdr_resultats',
            field=models.TextField(blank=True, verbose_name='Résultats attendus (un par ligne)'),
        ),
        migrations.AddField(
            model_name='moduleformation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description du module'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='categorie',
            field=models.CharField(choices=[('gis', 'SIG & QGIS'), ('teledetection', 'Télédétection'), ('webmapping', 'Cartographie Web'), ('collecte', 'Collecte de données'), ('python', 'Python & Géomatique'), ('autre', 'Autre')], default='gis', max_length=20),
        ),
        migrations.AlterField(
            model_name='formation',
            name='description_courte',
            field=models.TextField(verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='duree',
            field=models.CharField(blank=True, max_length=60, verbose_name='Durée (ex : 5 jours / 40h)'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='est_disponible',
            field=models.BooleanField(default=False, verbose_name="Disponible à l'inscription"),
        ),
        migrations.AlterField(
            model_name='formation',
            name='modalite',
            field=models.CharField(choices=[('presentiel', 'Présentiel'), ('enligne', 'En ligne'), ('hybride', 'Hybride')], default='presentiel', max_length=12),
        ),
        migrations.AlterField(
            model_name='formation',
            name='prix',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prix (FCFA)'),
        ),
        migrations.AlterField(
            model_name='formationsindexpage',
            name='intro',
            field=models.TextField(blank=True, default='Des formations pratiques animés par des experts terrain.'),
        ),
        migrations.AlterField(
            model_name='formationsindexpage',
            name='lms_url',
            field=models.URLField(blank=True, default='https://learn.innovgeomatic.com'),
        ),
        migrations.AlterField(
            model_name='formationsindexpage',
            name='stat_formes',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='formationsindexpage',
            name='stat_programmes',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='formationsindexpage',
            name='stat_satisfaction',
            field=models.PositiveIntegerField(default=95),
        ),
        migrations.AlterField(
            model_name='moduleformation',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre du module'),
        ),
        migrations.CreateModel(
            name='DocumentFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du document')),
                ('taille', models.CharField(blank=True, max_length=20, verbose_name='Taille (ex: 245 Ko)')),
                ('fichier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Fichier')),
                ('formation', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='formations.formation')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormateurFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('initiales', models.CharField(max_length=3, verbose_name='Initiales')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('role', models.CharField(max_length=200, verbose_name='Rôle / poste')),
                ('competences', models.CharField(blank=True, max_length=300, verbose_name='Compétences (séparées par virgules)')),
                ('formation', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='formateurs', to='formations.formation')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeconModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre de la leçon')),
                ('est_projet', models.BooleanField(default=False, verbose_name='Projet / évaluation finale')),
                ('module', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='formations.moduleformation')),
            ],
            options={
                'verbose_name': 'Leçon',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrerequisFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('texte', models.CharField(max_length=200, verbose_name='Prérequis')),
                ('requis', models.BooleanField(default=True, verbose_name='Requis (coché) / Non requis (décoché)')),
                ('formation', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequis', to='formations.formation')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
